# Generated by Django 4.2.4 on 2023-08-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_food_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='kind',
            field=models.CharField(choices=[('HQP', 'High-quality protein '), ('HQPF', 'High-quality protein with fats'), ('CC', 'Complex carbohydrates'), ('SC', 'Simple carbohydrates'), ('SC', 'Simple carbohydrates'), ('F', 'Fiber')], max_length=4),
        ),
    ]
